import { migrate } from 'drizzle-orm/postgres-js/migrator';
import path from 'node:path';
import { db } from './index';

/**
 * Run all pending Drizzle migrations.
 *
 * Migrations are read from the `src/db/migrations` directory which is
 * generated by `drizzle-kit generate`.
 *
 * This module can be executed directly:
 *   npx tsx src/db/migrate.ts
 *
 * Or imported and called programmatically during application startup.
 */
export async function runMigrations(): Promise<void> {
  const migrationsFolder = path.resolve(__dirname, 'migrations');

  console.log(`[migrate] Running migrations from ${migrationsFolder}`);

  await migrate(db, { migrationsFolder });

  console.log('[migrate] All migrations applied successfully.');
}

// Allow running as a standalone script.
const isMain = process.argv[1]?.includes('migrate');
if (isMain) {
  runMigrations()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error('[migrate] Migration failed:', error);
      process.exit(1);
    });
}
